Action handling
oetiker/callbackery pull request #155
Opened 2021-05-02 11:41 UTC by zaucker

- remove unnecessary warning for upload
- debug warning for undefined action

2021-05-02 13:43 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js
> +                    this.debug('Undefined action');
this is the default case ... handled on line 57 for all undefined actions ... nur just the 'undefined action ...

2021-05-02 13:43 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js
> +                            break;
ok

2021-05-05 09:05 UTC, oetiker requested changes

2021-05-05 09:05 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js
> -                            }
warum muessen die timer nicht mehr gestoppt werden ?

2021-05-05 09:49 UTC, zaucker commented
Ich möchte das mit den `modelSelection` für den Moment noch drin lassen, bis ich Camas umgebaut habe.

2021-05-05 09:50 UTC, zaucker commented
Die Timer werden im disappear event bereits gestoppt. Reicht das nicht?

2021-05-05 10:02 UTC, oetiker commented
> Die Timer werden im disappear event bereits gestoppt. Reicht das nicht?

ah ok ... in dem fall waere wohl noch gut zu testen ob die timeId auch gesetzt ist ... oder macht das nichts wenn der 'leer' ist ?

2021-05-05 10:02 UTC, oetiker commented
> Ich möchte das mit den `modelSelection` für den Moment noch drin lassen, bis ich Camas umgebaut habe.

okee ...

2021-05-05 10:04 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js
> +                    if (s.set && s.set.modelSelection) {
```suggestion
                    // to be removed as soon as @zaucker has cleaned up the cama appliaction
                    // 2021-05-05
                    if (s.set && s.set.modelSelection) {
```

2021-05-05 11:24 UTC, zaucker reviewed
> > Die Timer werden im disappear event bereits gestoppt. Reicht das nicht?
> 
> ah ok ... in dem fall waere wohl noch gut zu testen ob die timeId auch gesetzt ist ... oder macht das nichts wenn der 'leer' ist ?

Done, testen schadet sicher nicht.

2021-05-05 11:25 UTC, zaucker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/form/Auto.js
> +                    if (s.set && s.set.modelSelection) {
Done.

2021-05-05 11:53 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js
> +                            }
```suggestion
                            if (autoTimerId) {
                                autoTimer.stop(autoTimerId);
                                autoTimerId = null;
                            }
```

2021-05-05 11:53 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js
> +                                timer.stop(timerId);
```suggestion
                                timer.stop(timerId);
                                timerId = null;
```

2021-05-05 12:03 UTC, zaucker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js
> +                            }
Done

2021-05-05 12:03 UTC, zaucker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js
> +                                timer.stop(timerId);
Done

2021-05-05 13:48 UTC, merged