Make URL form setting consistent with URL action calling
oetiker/callbackery pull request #194
Opened 2021-12-30 09:38 UTC by zaucker

Allow form entries from URL with
```
        {
            key    => 'nevis_test',
            label  => trm('Test'),
            widget => 'text',
            set    => {
                required => true,
                maxWidth => 300,
            },
            urlFormKey => 'test',
        },
```
in backend with URL `http://localhost:7181/#app=HINPassword;test=test`.

**Note:** Backward-incompatible change (of none-documented feature).

2021-12-31 14:39 UTC, oetiker commented
I would suggest to call the url data functionality from within the loadData function, and thus merge any data coming from the server with the data given on the url before calling setData ... in this way any formReconf will get called as if the data came from the backend, and no strange things will happen from calling setData twice.

2021-12-31 14:43 UTC, zaucker commented
> I would suggest to call the url data functionality from within the loadData function, and thus merge any data coming from the server with the data given on the url before calling setData ... in this way any formReconf will get called as if the data came from the backend, and no strange things will happen from calling setData twice.
> 
> 

But then it will be called on every `_loadData()` and not just on appear. I guess this would probably work as the URL parameters are removed upon processing the first time.
Is this what you want?

2021-12-31 15:00 UTC, oetiker commented
no, the reason I am saying it is that loadData may cause formReconf and this may depend on the data entered in the form ... and if it gets filled with server data first, the reaction might be undesirable ... 

hence I would merge the data

but yes guarding against repeated action is certainly a valid thing ... 

the reason the 'original' code worked was because I never used it in connection with existing data

2021-12-31 16:03 UTC, zaucker commented
I left the callback in the appear handler, but merge the backend and urlData before setting the form.

2022-01-02 14:50 UTC, oetiker requested changes
ich wuerde nach moeglichkeit versuchen etwas weniger inline code zu machen ...

2022-01-02 14:50 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Form.js
> +        _loadData: function(callback){
```suggestion
        _getUrlData: function () {
                    let data    = {};
                    let gotData = false;
                    let config  = callbackery.data.Config.getInstance();
                    this._urlFormElements.forEach(urlFormElement => {
                        let urlValue = config.getUrlConfigValue(urlFormElement.urlKey);
                        if (urlValue) {
                            data[urlFormElement.formKey] = urlValue;
                            // only do it once for the time being
                            config.removeUrlConfigEntry(urlFormElement.urlKey);
                            gotData = true;
                        }
                    });
                    return data;
                }
         }
        _loadData: function(mergeUrlData){
```

2022-01-02 14:50 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Form.js
> +                    }
```suggestion
                    if (getUrlData) {
                        urlData = this._getUrlData();
                        if (!data) {
                            data = urlData;
                        }
                        else {
                            Object.assign(data, urlData);
                        }
                    }
```

2022-01-02 14:50 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Form.js
> +                    return data;
```suggestion
            this._loadData(true);
```

2022-01-02 14:50 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Form.js
> +            );
```suggestion
```

2022-01-02 15:41 UTC, zaucker commented
> ich wuerde nach moeglichkeit versuchen etwas weniger inline code zu machen ...

Suggestions comitted.

2022-01-02 16:05 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Form.js
> +         }
```suggestion
         },
```

2022-01-02 16:06 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Form.js
>                  }
```suggestion
```

2022-01-02 16:08 UTC, oetiker approved these changes

2022-01-02 16:09 UTC, merged