make callbackery work better on mobile
oetiker/callbackery pull request #218
Opened 2023-08-28 15:37 UTC by oetiker

* collaps navar buttons into menu
* move labels over form fields

2023-08-29 07:12 UTC, zaucker requested changes
Some cosmetical changes

2023-08-29 07:12 UTC, zaucker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js
> +                                                }
indentation

2023-08-29 07:12 UTC, zaucker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Action.js
> +                            this._mmButtonMap[btCfg.key]=mmButton;
s/=/ = /

2023-08-29 07:12 UTC, zaucker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Form.js
> +
Trailing spaces

2023-08-29 07:12 UTC, zaucker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/plugin/Table.js
> +	        return toolbar;
Indentation

2023-08-29 11:11 UTC, zaucker approved these changes

2023-08-29 16:46 UTC, zaucker approved these changes

2023-09-07 06:34 UTC, maettu commented on CHANGES
> + - make table columns with flex with work on mobile devices
I think the second "with" should be removed.

2023-11-27 13:08 UTC, merged