Custom header
oetiker/callbackery pull request #66
Opened 2019-11-05 10:24 UTC by zaucker

- Desktop gets headerWidget from Application
- Application returns "builtin" widget

2019-11-05 11:00 UTC, oetiker requested changes

2019-11-05 11:00 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/Application.js
>          }
kannst du bitte den footer auch gleich machen

2019-11-05 11:15 UTC, zaucker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/Application.js
>          }
Done.

2019-11-05 12:24 UTC, oetiker requested changes

2019-11-05 12:24 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Desktop.js
> +        this.add(qx.core.Init.getApplication().getHeaderWidget());
```suggestion
        var app = qx.core.Init.getApplication();
        this.add(app.getHeaderWidget());
```

2019-11-05 12:24 UTC, oetiker commented on lib/CallBackery/qooxdoo/callbackery/source/class/callbackery/ui/Desktop.js
> +        this.add(qx.core.Init.getApplication().getFooterWidget());
```suggestion
        this.add(app.getFooterWidget());
```

2019-11-06 09:15 UTC, oetiker approved these changes

2019-11-06 09:15 UTC, merged